### ISSUE TITLE
Add videos of Better Science for Future Us to YouTube, Julie's & Stef's

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/approach-guide#75]
from SWRCB and Fred Hutch Cohorts

@jules32 What do you think about me adding your full 15mins for SWRCB and from mine just my individual part?

**Comment by jules32** [comment]
Sure that sounds great Stef, thanks!

**Comment by stefaniebutland** [comment]
videos trimmed and uploaded to YouTube, but couldn't make further edits e.g. to make videos public, as YouTube kept giving errors

**Comment by stefaniebutland** [comment]
@jules32 
1. Can you please set [our 2 Better Science videos](https://studio.youtube.com/channel/UCFIy4WiSkf8Zilh5nbh2PdQ/videos/upload?filter=%5B%5D&sort=%7B%22columnType%22%3A%22date%22%2C%22sortOrder%22%3A%22DESCENDING%22%7D) to `public`? I'm not able to. Maybe it's permissions. (screenshot below)

2. Do you want yours listed in [Lesson Series - Better science](https://openscapes.github.io/series/core-lessons/better-science.html) under a new "Video Stories" callout below Slides callout? 
  - yours is the full ~20min from SWRCB, mine is just my intro. 
  - others to add? e.g.  ask Jeff for permission?

![Image](https://github.com/Openscapes/approach-guide/assets/11927811/18db2004-f4b7-4ade-8b2e-f3436d6fa78b)

**Comment by jules32** [comment]
Hi @stefaniebutland 

1. We've played with permissions and you are indeed able to set to Public – but there is a step you have to do first (and it silently errors/won't let you otherwise). Click on the name of the video and it will open an upload dialog box; there are questions you must answer before you can make public. One question is "is this for kids"? and the answer is no. Then, you can change the Visibility to Public.
2. That sounds great! Let's stick with these two now and can revisit with others going forward.

Thank you!

**Comment by stefaniebutland** [comment]
addressed in https://github.com/Openscapes/series/pull/36
